api_controllers:
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
    type: attribute

admin_controllers:
    resource:
        path: ../src/Controller/Admin
        namespace: App\Controller\Admin
    type: attribute
